version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_orders
    environment:
      POSTGRES_DB: deputados_db
      POSTGRES_USER: agnaldo
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
