version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_desafio
    environment:
      POSTGRES_DB: deputadosdb
      POSTGRES_USER: agnaldo
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
