// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/deputado.proto

package deputadopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_proto_deputado_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_deputado_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_deputado_proto_rawDescGZIP(), []int{0}
}

type Deputado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Partido       string                 `protobuf:"bytes,3,opt,name=partido,proto3" json:"partido,omitempty"`
	NumeroVotos   int64                  `protobuf:"varint,4,opt,name=numero_votos,json=numeroVotos,proto3" json:"numero_votos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deputado) Reset() {
	*x = Deputado{}
	mi := &file_internal_proto_deputado_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deputado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deputado) ProtoMessage() {}

func (x *Deputado) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_deputado_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deputado.ProtoReflect.Descriptor instead.
func (*Deputado) Descriptor() ([]byte, []int) {
	return file_internal_proto_deputado_proto_rawDescGZIP(), []int{1}
}

func (x *Deputado) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Deputado) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Deputado) GetPartido() string {
	if x != nil {
		return x.Partido
	}
	return ""
}

func (x *Deputado) GetNumeroVotos() int64 {
	if x != nil {
		return x.NumeroVotos
	}
	return 0
}

type DeputadoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deputados     []*Deputado            `protobuf:"bytes,1,rep,name=deputados,proto3" json:"deputados,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeputadoList) Reset() {
	*x = DeputadoList{}
	mi := &file_internal_proto_deputado_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeputadoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeputadoList) ProtoMessage() {}

func (x *DeputadoList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_deputado_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeputadoList.ProtoReflect.Descriptor instead.
func (*DeputadoList) Descriptor() ([]byte, []int) {
	return file_internal_proto_deputado_proto_rawDescGZIP(), []int{2}
}

func (x *DeputadoList) GetDeputados() []*Deputado {
	if x != nil {
		return x.Deputados
	}
	return nil
}

var File_internal_proto_deputado_proto protoreflect.FileDescriptor

const file_internal_proto_deputado_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/deputado.proto\x12\bdeputado\"\a\n" +
	"\x05Empty\"k\n" +
	"\bDeputado\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x18\n" +
	"\apartido\x18\x03 \x01(\tR\apartido\x12!\n" +
	"\fnumero_votos\x18\x04 \x01(\x03R\vnumeroVotos\"@\n" +
	"\fDeputadoList\x120\n" +
	"\tdeputados\x18\x01 \x03(\v2\x12.deputado.DeputadoR\tdeputados2K\n" +
	"\x0fDeputadoService\x128\n" +
	"\rListDeputados\x12\x0f.deputado.Empty\x1a\x16.deputado.DeputadoListBAZ?github.com/agnaldopidev/deputados-app/internal/proto/deputadopbb\x06proto3"

var (
	file_internal_proto_deputado_proto_rawDescOnce sync.Once
	file_internal_proto_deputado_proto_rawDescData []byte
)

func file_internal_proto_deputado_proto_rawDescGZIP() []byte {
	file_internal_proto_deputado_proto_rawDescOnce.Do(func() {
		file_internal_proto_deputado_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_deputado_proto_rawDesc), len(file_internal_proto_deputado_proto_rawDesc)))
	})
	return file_internal_proto_deputado_proto_rawDescData
}

var file_internal_proto_deputado_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_deputado_proto_goTypes = []any{
	(*Empty)(nil),        // 0: deputado.Empty
	(*Deputado)(nil),     // 1: deputado.Deputado
	(*DeputadoList)(nil), // 2: deputado.DeputadoList
}
var file_internal_proto_deputado_proto_depIdxs = []int32{
	1, // 0: deputado.DeputadoList.deputados:type_name -> deputado.Deputado
	0, // 1: deputado.DeputadoService.ListDeputados:input_type -> deputado.Empty
	2, // 2: deputado.DeputadoService.ListDeputados:output_type -> deputado.DeputadoList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_deputado_proto_init() }
func file_internal_proto_deputado_proto_init() {
	if File_internal_proto_deputado_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_deputado_proto_rawDesc), len(file_internal_proto_deputado_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_deputado_proto_goTypes,
		DependencyIndexes: file_internal_proto_deputado_proto_depIdxs,
		MessageInfos:      file_internal_proto_deputado_proto_msgTypes,
	}.Build()
	File_internal_proto_deputado_proto = out.File
	file_internal_proto_deputado_proto_goTypes = nil
	file_internal_proto_deputado_proto_depIdxs = nil
}
