// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/proto/deputado.proto

package deputadopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeputadoService_ListDeputados_FullMethodName = "/deputado.DeputadoService/ListDeputados"
)

// DeputadoServiceClient is the client API for DeputadoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeputadoServiceClient interface {
	ListDeputados(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeputadoList, error)
}

type deputadoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeputadoServiceClient(cc grpc.ClientConnInterface) DeputadoServiceClient {
	return &deputadoServiceClient{cc}
}

func (c *deputadoServiceClient) ListDeputados(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeputadoList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeputadoList)
	err := c.cc.Invoke(ctx, DeputadoService_ListDeputados_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeputadoServiceServer is the server API for DeputadoService service.
// All implementations must embed UnimplementedDeputadoServiceServer
// for forward compatibility.
type DeputadoServiceServer interface {
	ListDeputados(context.Context, *Empty) (*DeputadoList, error)
	mustEmbedUnimplementedDeputadoServiceServer()
}

// UnimplementedDeputadoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeputadoServiceServer struct{}

func (UnimplementedDeputadoServiceServer) ListDeputados(context.Context, *Empty) (*DeputadoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeputados not implemented")
}
func (UnimplementedDeputadoServiceServer) mustEmbedUnimplementedDeputadoServiceServer() {}
func (UnimplementedDeputadoServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeputadoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeputadoServiceServer will
// result in compilation errors.
type UnsafeDeputadoServiceServer interface {
	mustEmbedUnimplementedDeputadoServiceServer()
}

func RegisterDeputadoServiceServer(s grpc.ServiceRegistrar, srv DeputadoServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeputadoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeputadoService_ServiceDesc, srv)
}

func _DeputadoService_ListDeputados_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeputadoServiceServer).ListDeputados(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeputadoService_ListDeputados_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeputadoServiceServer).ListDeputados(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DeputadoService_ServiceDesc is the grpc.ServiceDesc for DeputadoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeputadoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deputado.DeputadoService",
	HandlerType: (*DeputadoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeputados",
			Handler:    _DeputadoService_ListDeputados_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/deputado.proto",
}
