// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Deputado struct {
	ID      string `json:"id"`
	Nome    string `json:"nome"`
	Partido string `json:"partido"`
	Votos   int    `json:"votos"`
}

type Query struct {
}
