package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"github.com/agnaldopidev/deputados-app/internal/graph/generated"
	"github.com/agnaldopidev/deputados-app/internal/graph/model"
)

// ListDeputados is the resolver for the listDeputados field.
func (r *queryResolver) ListDeputados(ctx context.Context) ([]*model.Deputado, error) {
	rows, err := r.DB.Query("SELECT id, nome, partido, votos FROM deputados ORDER BY votos DESC")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var deputados []*model.Deputado

	for rows.Next() {
		var d model.Deputado
		if err := rows.Scan(&d.ID, &d.Nome, &d.Partido, &d.Votos); err != nil {
			return nil, err
		}
		deputados = append(deputados, &d)
	}

	return deputados, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
